# S3 Endpoint Configuration
endpoint_url: 'https://eodata.dataspace.copernicus.eu'
endpoint_stac: 'https://stac.dataspace.copernicus.eu/v1/'
bucket_name: 'eodata'

bands:
  - 'B02'
  - 'B03'
  - 'B04'

# Query Configuration
query:
  bbox:
    - 3.2833
    - 45.3833
    - 11.2
    - 50.1833

  start_date: '2024-06-01'
  end_date: '2024-10-15'

  max_items: 1000
  max_cloud_cover: 30

